### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**

### CODE REVIEW

**Comment by javier-godoy** [comment]
af9c706 `Close #8`
dc91f66 remove link from subject
36ed635 remove link from subject

**Review by javier-godoy — DISMISSED** [review]
Changes requested

**Comment by javier-godoy** [comment]
@ngonzalezpazFC Please review

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC Please review

LGTM

**Pull request merged**
